spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8085
          predicates:
            - Path=/users/**
        - id: task-service
          uri: http://localhost:8083
          predicates:
            - Path=/task/**
        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=/notifications/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
